language: cpp

compiler:
- gcc

os:
- linux


install:
    - sudo apt-get update
    - sudo apt-get install libeigen3-dev
    - git clone https://github.com/coin-or/qpOASES.git
    - cd qpOASES 
    - mkdir build && cd build 
    - cmake .. -DCMAKE_CXX_FLAGS=-fPIC
    - sudo make install -j8
    - cd ../../ 
    
script: 
    - cmake ./cpp
    - make -j8 && sudo make install -j8     
    - mkdir ./cpp/test/build
    - cd ./cpp/test/build && cmake .. && make -j8
    - ./test_pin
